### ISSUE TITLE
Remove inline styling

### ISSUE THREAD

**Issue by ydlamba** [openwisp/OpenWISP-Website#16]
In spite of having external stylesheets, many elements have inline styles. There are a bunch of reasons for which we should avoid using them. Few of them are:

- They are very hard to maintain. Separate files always help to maintain the application.
- Reduce code readability.
- Small performance issue.
- Cannot be reused and increase code lines.
- Inline styles are not good for SEO (I don't know much about it).
- In brief, using inline styles has been considered as a bad practice for a long time.

**Comment by nemesisdesign** [comment]
We have a new website design which is going to be deployed somewhen in the future. If you want to help us out please focus on the software projects, issues, chat, mailing list and on the documentation.
Thank you @ydlamba
