### ISSUE TITLE
[activity] Infinity seconds ago

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/OpenWISP-Website#46]
When new items are published on the activity feed, they appear with "Infinity seconds ago".

**Comment by IAmAMissingColon** [comment]
Hi there ! @nemesisdesign I can produce this error ! but do we want something like "just now" as a replacement of "Infinity seconds ago". :smile:

**Comment by nemesisdesign** [comment]
@IAmAMissingColon "Just now" is good, thanks!

**Comment by IAmAMissingColon** [comment]
@nemesisdesign can I work on this when GCI Starts ?

**Comment by nemesisdesign** [comment]
@IAmAMissingColon if that doens't get solved earlier by somone else, you can do as you like
