### ISSUE TITLE
Wording Changes

### ISSUE THREAD

**Issue by thejwzhang** [openwisp/OpenWISP-Website#5]
I have some suggestions to change the header wordings so they are better understandable in English.

1. Change "What is" to "About OpenWISP"
2. Change "About us" to "About the Team"
3. Change "Support" to "Help" because support makes it seem more like a donations page.
4. On the History page, I would suggest translating the organization names into English so English speakers can better understand the variety of organizations and groups using OpenWISP

**Comment by HargovindArora** [comment]
@nemesisdesign Can you please look at the 4th point? Can it be done?

**Comment by nemesisdesign** [comment]
yea it can be done

**Comment by HargovindArora** [comment]
@thejwzhang Thanks for your work, can you please suggest one more valuable change to our site. That will be very helpful to us! :-)

**Comment by xamfy** [comment]
@HargovindArora can the task be accepted?
