### ISSUE TITLE
Remove background animation to improve performance and accessibility

### ISSUE THREAD

**Issue by okraits** [openwisp/OpenWISP-Website#50]
The index page on https://openwisp.org/ contains an animation in the background which is unfavourable because of several reasons:

* When using a remote desktop software like X2Go (https://wiki.x2go.org/), visiting the page makes the browser unresponsive and thus effectively unusable
* Visiting the page (locally, not through X2Go) increases the system load on my Core i7 Quadcore laptop from 0.01 to ~ 0.6 (55 % CPU usage only for the browser displaying the page!)
* From what I've learned about good, clean and slim webdesign, automatic and continous animations are considered bad design

Therefore I propose to replace the animation with a static background, for example a solid color background or a calm image.

**Comment by vidhideshmukh** [comment]
hey!! , i am intrested to solve solve this issue can you assign me this task.

**Comment by okraits** [comment]
@vidhideshmukh Great that you want to start to work on it!

@nemesisdesign What do you think about this issue and potential solutions?

**Comment by vidhideshmukh** [comment]
instead of that animation we can use a good image background

**Comment by nemesisdesign** [comment]
I'd try to maintain the same pattern with a vector image or something similar, alternatively, the same canvas JS code but without the animation. I would try also a slower animation to see if you notice the same problem @okraits.

**Comment by prsndp** [comment]
Hey, I want to work on this issue.

**Comment by okraits** [comment]
@nemesisdesign I would prefer a static image which could be used for the background, maybe tiled. JS code for the background is overkill IMO. It needs to be maintained and can include bugs and security issues.

**Comment by sirsambhav221** [comment]
@okraits can I work on this issue??

**Comment by IayushCoderJOD** [comment]
hey can I work on this issue @okraits it's quite long since this issue is open

**Comment by okraits** [comment]
@nemesisdesign Are you ok with using a static vector image?

**Comment by nemesisdesign** [comment]
I am ok with an alternative background image which resizes according to the screen size.

**Comment by nemesifier** [comment]
The new website design solved this.
