### ISSUE TITLE
[bug] Content in activity feed is not sanitized

### ISSUE THREAD

**Issue by nemesifier** [openwisp/OpenWISP-Website#54]
Any content which comes in the form of HTML or JS from github should be sanitized (eg: convert special characters to html entities) to avoid the possibility from third parties to trigger any code by looking at the [activity feed](https://openwisp.org/activity.html).

Eg: the following shouldn't happen (`<input>` should be rendered as `&lt;input&gt;` and not as an actual HTML input).
![Screenshot from 2021-11-11 18-21-04](https://user-images.githubusercontent.com/841044/141382981-2b56f2cb-f2c7-47b1-abac-84dc82dee0a9.png)

**Comment by yashikajotwani12** [comment]
I would like to work on this.

**Comment by nemesisdesign** [comment]
@avvicky go for it.

**Comment by kunal232i** [comment]
Hello @nemesifier, I observed that issue #54 related to unsanitized content in the activity feed is still unresolved. I'm keen on contributing to its resolution. Kindly let me know if it's possible for me to take this up. Looking forward to your guidance. Thank you!

**Comment by nemesifier** [comment]
Sure go for it @kunal232i :+1:

**Comment by kunal232i** [comment]
Hey @nemesifier, I have resolved the issue regarding the [bug] 'Content in activity feed is not sanitized' in PR #75. Could you please look into it? Thank you
