### ISSUE TITLE
add an Error 404 page

### ISSUE THREAD

**Issue by khareyash05** [openwisp/OpenWISP-Website#55]
I would like to add an error 404 page to the website

**Comment by sara-naeem-cs** [comment]
Hi @khareyash05 I'd like to work on this issue please

**Comment by IayushCoderJOD** [comment]
hey I've created the error 404  page , where to link the page
??
Like when should we display this 404 page?
@khareyash05

**Comment by IayushCoderJOD** [comment]
![image](https://user-images.githubusercontent.com/86391985/214778531-6ddbd9fa-e2b4-47bc-97de-43d00c79321d.png)
I had created the page tho

**Comment by nemesisdesign** [comment]
@IayushCoderJOD make sure the header with logo and menu, as well as the footer, are included, otherwise the 404 page is incomplete.

**Comment by IayushCoderJOD** [comment]
@nemesisdesign  got it sir , actually I implemented the error 404 page with 5 second set timeout and after 5 sec it automatically goes to the home page of the website but if you want me to do the same as you mentioned above I can do it.. Please confirm.

Thanks.
