### ISSUE TITLE
'The Code' page should include OpenWISP Contributing Guidelines

### ISSUE THREAD

**Issue by aryanbhasin** [openwisp/OpenWISP-Website#6]
<img width="969" alt="screen shot 2017-11-29 at 11 21 59 pm" src="https://user-images.githubusercontent.com/21118039/33390653-913e1956-d55c-11e7-86f1-5bc082b32ca0.png">

"The Code" page should include OpenWISP's Contributing Guidelines mentioned on [this page](http://openwisp.io/docs/developer/contributing.html), or include a link to it.

Finding the Contributing Guidelines would be difficult for a new contributor, and adding this information to the webpage would make it more beginner-friendly.

**Comment by nemesisdesign** [comment]
Yea totally.

**Comment by aryanbhasin** [comment]
@nemesisdesign Should I add the link to the guidelines or add snippets as well?

**Comment by nemesisdesign** [comment]
Link to guidelines is fine, but I haven't understood what you mean for snippets

**Comment by aryanbhasin** [comment]
snippets as in the code snippet examples on the guidelines page, such as this one:
<img width="254" alt="screen shot 2017-11-29 at 11 42 55 pm" src="https://user-images.githubusercontent.com/21118039/33391438-10e202a6-d55f-11e7-8b1e-3ab2c7c84026.png">

**Comment by aryanbhasin** [comment]
@nemesisdesign Should I also add the favicons for the website as I saw an open issue on that

**Comment by nemesisdesign** [comment]
link to guidelines is fine, leave the favicon to the person who is handling that, I've noticed you abandoned the task or am I wrong?

**Comment by aryanbhasin** [comment]
Sorry, I was solving the travis build fail task, I thought I would return to this as soon as I would finish that. I'll claim this one again.
