### ISSUE TITLE
Remove extra close icon on the popup

### ISSUE THREAD

**Issue by Pranshu1902** [openwisp/OpenWISP-Website#69]
The extra close icon on the top right doesn't fit with the website design. It would be better to remove it and only keep the red cross at the bottom right
![image](https://user-images.githubusercontent.com/70687348/229307087-d008b8b4-9ea3-4152-9178-50dd51d76a98.png)

**Comment by Tweniee** [comment]
share the steps to get on this page

**Comment by Pranshu1902** [comment]
@Tweniee The issue was raised months ago, that entire rating component has been removed
