### ISSUE TITLE
Implement Sticky Navigation on Scroll

### ISSUE THREAD

**Issue by sarcaxticlarka** [openwisp/OpenWISP-Website#76]
Description:
I'd like to contribute to this project by suggesting an enhancement. Currently, the navigation section is not visible when scrolling. I propose implementing a feature where the navigation becomes visible when users scroll down the page.

Proposed Changes:

Make the navigation section visible on scroll.
Benefits:

Improved user experience.
Easier navigation while scrolling.
Enhances the website's usability.
Technical Details:
This can be achieved using CSS and JavaScript.

Acceptance Criteria:

Navigation becomes visible on scroll.
The feature works consistently on various browsers and devices.
No introduction of new issues.
I'm eager to discuss and collaborate on this enhancement. Your feedback is welcome.

**Comment by nemesifier** [comment]
We are currently focused on other tasks and we cannot dedicate bandwidth to this proposal, sorry.
